enabled evmos support + fixed decimals
eco-stake/restake pull request #67
Opened 2022-03-06 18:51 UTC by evmosius

TLDR: Added an optional `decimals` field to network.json, decimals default to 1e6 unless it is overridden (in the case of evmos 1e18).

Unsure of how fix the error below, some insight would be appreciated.

[ ] Fix `Failed to broadcast: Unsupported type: '/ethermint.types.v1.EthAccount'` Error
<img width="723" alt="Screen Shot 2022-03-06 at 10 48 55 AM" src="https://user-images.githubusercontent.com/100507618/156937658-bebb79ba-83f1-40ed-a9f7-0255e5204b45.png">

2022-03-06 19:09 UTC, tombeynon commented
This is incredible, thanks so much for doing this. Desperately want to get Evmos onto the site but been juggling other fixes etc this weekend 💥 

I've just looked into the unsupported type. I believe the solution will be to use this repository to provide the additional message types we need to handle Evmos transaction. There is a Delegate message builder which is the main thing we need. 

https://github.com/tharsis/evmosjs

I can probably spend some time on this tomorrow unless you're comfortable with cosmjs + the different messages. 

Btw could we take the package-json.lock change out of this PR, unless there's a specific reason we should downgrade to lockfile version 1?

2022-03-06 20:00 UTC, tombeynon commented
cc @Galadrin for CRO - is that `1e8` needed here?

2022-03-06 20:13 UTC, evmosius commented
@tombeynon Thanks for the review. Unfortunately I'm not particularly familiar with cosmjs + different messages. It would be greatly appreciated if you can implement the delegate message builder.

I've also nixed the `package-lock.json` change.

2022-03-06 20:42 UTC, tombeynon commented
Very happy to, I'll update you here ASAP. Thanks again for the denom work 👌🏻

2022-03-06 23:04 UTC, tombeynon commented
Sifchain is `1e18` for my notes. This info is available in the chain-registry assetlists

2022-03-07 07:15 UTC, Sdpierret commented
> cc @Galadrin for CRO - is that `1e8` needed here?

yes, basecro is 8 decimal

2022-03-07 07:26 UTC, Sdpierret commented
@evmosius  I made a change proposal on your branch ;)

2022-03-07 10:30 UTC, Galadrin requested changes

2022-03-07 10:30 UTC, Galadrin commented on src/networks.json
> +    "decimals": 1e18,
can be fine to keep the decimal number from chain-registry

"decimals": 18

2022-03-07 10:30 UTC, Galadrin commented on src/components/DelegateForm.js
> +          amount: coin(parseInt(parseFloat(amount) * d), this.props.network.denom),
amount: coin(parseInt(parseFloat(amount) * math.pow(10, d), this.props.network.denom),

2022-03-07 10:30 UTC, Galadrin commented on src/components/DelegateForm.js
> +    const d = decimals ? decimals : 1e6;
const d = decimals ? decimals : 6;

2022-03-07 10:30 UTC, Galadrin commented on src/components/Coins.js
> +    if (!decimals) {
if (!decimals) {
      decimals = 6
    }
    return _.round(coins.amount / math.pow(10, decimals), 6)

2022-03-07 20:16 UTC, tombeynon commented
@Galadrin thank you for your suggestions and @evmosius hugely appreciate the initial work.

I'm going to merge the decimals fix in as-is and keep Evmos disabled for now, and work on the `ethermint.types.v1.EthAccount` bug in the linked issue. I'll get this sorted asap @evmosius

2022-03-07 20:29 UTC, merged